set(headers ${headers}
	src/PCH.h
    src/log.h
    src/util.h
    src/settings.h
    src/InputManager.h
    src/InputDispatcher.h
    src/MenuChecker.h
    src/higgsinterface001.h
    src/DoubleTapDetector.h
    src/DressupMenuManager.h
    src/InventoryManager.h
    src/NpcUtils.h
    src/SpellWheelInterface.h
    src/api/ThreeDUIInterface001.h
    src/dressup/ArmorModManager.h
    src/dressup/DressupTransaction.h
    src/dressup/DressHistory.h
    src/dressup/GalleryStateManager.h
    src/dressup/ItemEquipHelper.h
    src/dressup/KeywordCategoryManager.h
    src/dressup/UndressManager.h
    src/dressup/OutfitLockManager.h
    src/dressup/OutfitSlotManager.h
    src/dressup/WeaponLockManager.h
    src/dressup/OutfitFormBackend.h
    src/dressup/SeverActionsCompat.h
    src/dressup/DeviceCompat.h
    src/dressup/PapyrusBridge.h
    src/util/VRNodes.h
    external/VRManagerAPI.h
    external/PapyrusVRTypes.h
    external/VRHookAPI.h
    external/PapyrusVRAPI.h
    external/OpenVRTypes.h
)
