set(sources ${sources}
    src/plugin.cpp
    src/InputManager.cpp
    src/MenuChecker.cpp
    src/higgsinterface001.cpp
    src/dressup/OutfitLockManager.cpp
    src/dressup/WeaponLockManager.cpp
    src/dressup/OutfitFormBackend.cpp
    src/dressup/SeverActionsCompat.cpp
    src/dressup/DeviceCompat.cpp
    src/dressup/PapyrusBridge.cpp
    src/dressup/FormKeyUtil.cpp
    src/dressup/KeywordCategoryManager.cpp
    src/api/ThreeDUIInterface001.cpp
    src/api/ThreeDUIActorMenu.cpp
    src/api/DressUpInterface001.cpp
    src/api/DressUpInterface002.cpp
    external/PapyrusVRTypes.cpp
)
